### ISSUE TITLE
The Documentation folder is missing.

### ISSUE THREAD

**Issue by philderbeast** [DSSAT/dssat-csm-os#13]
In the [Structure of the code](https://github.com/DSSAT/dssat-csm-os#structure-of-the-code) section there's a tree showing, among other things, where to find the `Documentation` folder. The [Data](https://github.com/DSSAT/dssat-csm-os#data) section mentions documentation too. Is this folder missing in the source repository or is it a build output?

```
.
└── Data
    ├── Documentation
```

**Comment by chporter** [comment]
The documentation is included in the Windows install files, but it has not been included in the github repositories. We'll have to think about whether that makes sense to have a bunch of pdfs in a repository. I suppose it would be convenient for some people.

**Comment by frostbytten** [comment]
Maybe a dssat-csm-doc repo?

**Comment by philderbeast** [comment]
Do you build the `*.pdf` from source, such as LaTeX?

**Comment by chporter** [comment]
No, these are pdfs from published journal articles. Some are even old scanned images.

**Comment by philderbeast** [comment]
In this source repo could we add a readme at `/Data/Documentation/readme.md` that has links to those papers?

**Comment by chporter** [comment]
We have decided to build a separate document repo. Good idea to link them in this repo.
