### ISSUE TITLE
Need N2O.csv output

### ISSUE THREAD

**Issue by chporter** [DSSAT/dssat-csm-os#140]
Could simplify the output and only bring over the cumulative values. These are the most important. Do not bring over all the soil layer data. We will probably remove these from the standard output.

**Comment by chporter** [comment]
@JeffWhiteAZ needs this for analysis ASAP, but I told him it would probably be after the Germany workshop.

**Comment by fabiooliveira72** [comment]
Hi Cheryl! For sure I will do it. Also, it will be good to talk with you about it tomorrow as well. Thank you

**Comment by fabiooliveira72** [comment]
I already add this in my ToDos

**Comment by chporter** [comment]
Leave the daily values, but remove the soil layer data.
