### ISSUE TITLE
batch mode failure for SC

### ISSUE THREAD

**Issue by chporter** [DSSAT/dssat-csm-os#146]
When running the ALL.v48 file, the simulations stop after SXPG6801.SCX. 
When running just sugarcane, all is OK. 
When going from SXPG6801.SCX to AUTA8101.SUX, all is OK, so it seems to be the UFBG files. However, these run OK by themselves.

Just noting this here so we don't forget.

**Comment by chporter** [comment]
@fabiooliveira72 - this one is solved with your latest pull request, right?

**Comment by fabiooliveira72** [comment]
> @fabiooliveira72 - this one is solved with your latest pull request, right?

Yes, Cheryl. You can close this issue. Thank you.
