### ISSUE TITLE
Rice initialization issue?

### ISSUE THREAD

**Issue by chporter** [DSSAT/dssat-csm-os#152]
Run the attached batch file (DTSP8502.RIX, trt 1; UHIH1702.QUX, trt 8; then DTSP8502.RIX, trt 1 again).
[Custom_v48.txt](https://github.com/DSSAT/dssat-csm-os/files/7228108/Custom_v48.txt)

The simulation gives different results for rice simulation the 2nd time. 

I haven't had time to fully investigate, but some N variables (total inorganic N, N uptake, nitrification) are different near the end of the season. That's one clue, but more variables need to be investigated before we can draw conclusions. I'm guessing it's a plant module intitialization issue that only showed up after Quinoa genotype files were updated. (!).

**Comment by fabiooliveira72** [comment]
This issue was solved by merge: Initialized MULCHWATER subroutines local variables because of model Initialization issues

https://github.com/DSSAT/dssat-csm-os/tree/ef7979f8b5d36ead732f032414b732cb78b2ec46
