### ISSUE TITLE
Problem with path for OilCrop-Sunflower in CMakelists.txt

### ISSUE THREAD

**Issue by palderman** [DSSAT/dssat-csm-os#154]
The path for OilCrop-Sunflower in CMakelists.txt lacks a capital "C":

https://github.com/DSSAT/dssat-csm-os/blob/37d00a566e33571cc9997ea8dfc5788b4a6146bb/CMakeLists.txt#L507-L516

This is a problem for compiling on Linux (and possibly on Mac?). I'll submit a pull request in just a sec.

**Comment by chporter** [comment]
Solved with commit ebe02268a1a883e2ffa203094e7342ff881f3e68
