### ISSUE TITLE
A user guide with sphinx.

### ISSUE THREAD

**Issue by philderbeast** [DSSAT/dssat-csm-os#16]
In addition to the helpful pages already published on the [DSSAT](https://dssat.net/) site, please consider using [sphinx](https://www.sphinx-doc.org/en/master/) for making a users guide for this project. This could be published with [readthedocs.io](https://readthedocs.org/) or self-hosted at https://dssat.net/users-guide.

Here are some examples of users guides compiled this way.

https://docs.haskellstack.org
https://www.haskell.org/cabal/users-guide
https://flare-timing.readthedocs.io

**Comment by chporter** [comment]
Thanks for the great suggestions @philderbeast .

**Comment by fabiooliveira72** [comment]
Hi Philderbeast!

Thanks for your suggestion we already took notes about this technology and others that may be useful too. We will check on this!

Thank you!
