### ISSUE TITLE
Issue on CentOS installation

### ISSUE THREAD

**Issue by angelosnm** [DSSAT/dssat-csm-os#165]
I am getting the bellow error at "make" command.

![image](https://user-images.githubusercontent.com/28690845/143586046-6969b29e-914d-4783-a820-eb2a834afa05.png)

Reproduced the issue on an Ubuntu machine and build performed without any issues

**Comment by frostbytten** [comment]
Sorry I am not in town at the moment, but I believe the issue is that libm and libc are expected to be statically linked and therefore need to -static versions to be installed on CentOS (or any RHEL related distros).

**Comment by angelosnm** [comment]
> 

Thanks for your reply! This was the issue.
In fact, I was missing package "glibc-static".

I'm also writning down below the needed packages for the installation on CentOS machines for further reference puproses:

- gcc-gfortran 
- cmake 
- git (in case it is not already preinstalled)
- glibc-static

**Comment by GerritHoogenboom** [comment]
I am glad that you found the issue and we will address accordingly.
