### ISSUE TITLE
Negative RADSH

### ISSUE THREAD

**Issue by palderman** [DSSAT/dssat-csm-os#166]
@chporter and @kthorp ,

I'm getting floating point errors with the forage model related to the fact that `RADSH` is negative due to `ADDF` being negative in CANABS() in ETPHOT.for. When I uncomment the check for `ADDF < 0.0` (see below), the problem goes away. The issue seems to be limited to situations with very low LAI.

Is there a reason why the checks for negative numbers are commented out in CANABS() in ETPHOT.for? Is there any problem with allowing `ADDF`, `ADDFSL`, etc to be set to zero when the original calculation is negative? See here:

https://github.com/DSSAT/dssat-csm-os/blob/a20a2b5a0be76ad85f3a5f76434dcacc52a319cb/SPAM/ETPHOT.for#L1793-L1800

https://github.com/DSSAT/dssat-csm-os/blob/a20a2b5a0be76ad85f3a5f76434dcacc52a319cb/SPAM/ETPHOT.for#L1814-L1827

https://github.com/DSSAT/dssat-csm-os/blob/a20a2b5a0be76ad85f3a5f76434dcacc52a319cb/SPAM/ETPHOT.for#L1862-L1869

https://github.com/DSSAT/dssat-csm-os/blob/a20a2b5a0be76ad85f3a5f76434dcacc52a319cb/SPAM/ETPHOT.for#L1883-L1890

**Comment by fabiooliveira72** [comment]
Hi Dr. Alderman!

Yes, indeed. We have this problem right now. We had some problems with Canola experiments from Dr. White are having the same issue.

We are about the make a pull request to fix those issues. We need to check with a final testing if did not broke anything else.

Thank you so much,

Fabio Oliveira

**Comment by fabiooliveira72** [comment]
This issue was solved by merge Protections for Negative LAI and radiation absorbed by sunlit and shaded leaves

 https://github.com/DSSAT/dssat-csm-os/tree/d0c9faa89c7dc3b276197e3ea7cdca64d41bdc5b
