### ISSUE TITLE
Could not locate error file: ./MODEL.ERR

### ISSUE THREAD

**Issue by vineetk008** [DSSAT/dssat-csm-os#262]
Hi Developers,
After compiling and configuring the dscsm048 executable following msg came at my LINUX system:

-----------------------------------------------------------------------------                               

Could not locate error file: ./MODEL.ERR

Unknown ERROR. Error number:    90

File:                Line:     0 Error key: CSM
Additional information may be available in WARNING.OUT file.

-------------------------------------
1) Does it mean the executable file is not properly configured? Because when I run the model code, it says dscsm048 not find. 
2) I don't see any additional information in WARNING file except Run 0.
Thanks for any help.

**Comment by lpmorenoc** [comment]
Hi @vineetk008,
You can get the MODEL.ERR file from the DSSAT48 folder when you install DSSAT in a Windows environment. However, if you do not have that folder, you can find the files necessary to run the model here: https://github.com/DSSAT/dssat-csm-os/tree/develop/Data (including the MODEL.ERR file) and here https://github.com/DSSAT/dssat-csm-data. 
The error that you are getting is: `CSM      90
Runmode not specified or invalid`

About your question:
 How are you running the model? I am providing an example for running DSSAT using a batch file for the experiment EBPL8501.MZX  of maize which is available here https://github.com/DSSAT/dssat-csm-data/tree/develop/Maize:

Use the following command: `dscsm048 MZCER048 B DSSBatch.v48`. I am attaching an example of the batch file, but you will have to modify lines 11 to 14 based on the path where you put your experimental files (change the txt extension to .v48) [DSSBatch.txt](https://github.com/DSSAT/dssat-csm-os/files/9577765/DSSBatch.txt).
