### ISSUE TITLE
ADAT and MDAT in FileA

### ISSUE THREAD

**Issue by chporter** [DSSAT/dssat-csm-os#28]
Transferring this issue from the private repo. I'm not sure that it's been resolved yet. Have we differentiated between DOY and DAP in all FileAs?

from @palderman :
I'm going through some final (I hope) checking for the DSSAT R package I've put together and about to start writing up. Anyway, I've been noticing that a lot of the A files (files A?) that are in the DSSAT CSM repo have only 3-digit values in the columns for MDAT and ADAT. For example:

Barley/IEBR8201.BAA
Barley/MTBO7701.BAA
Canola/USON0801.CNA
Canola/USOT0801.CNA

I'm thinking that people have mislabeled those columns (should be ADAP or MDAP?), but I wanted to check to be sure I haven't missed something.

Some additional examples:

Chickpea/ITBW9205.CHA
Chickpea/ITBW9306.CHA

For these examples, it seems that the ADAT values might be simply day of year? In any case, there seems to be some problem.

from @GerritHoogenboom

Yes, that's correct. Currently FileA is read by the model only and there are smarts to associate the Year with the DOY value.

**Comment by fabiooliveira72** [comment]
Hi @palderman

I checked the subroutines in the model and the column names based on the source code.

If the FileA has ADAT and MDAT, the subroutine (usually OPHARV.for) will associate the name of the column with what has hard-coded.

Please see the subroutine MZ_OPHARV for Maize:

`!-----------------------------------------------------------------------
      ACOUNT = 22  !Number of FILEA headings.
!     Headings in FILEA for Measured data
      DATA OLAB /
     **&    'ADAT  ',     !1  DFLR** 
     &    'PD1T  ',     !2  IFPD 
     &    'PDFT  ',     !3  IFSD 
     **&    'MDAT  ',     !4  DMAT** 
     &    'HWAM  ',     !5  XGWT 
     &    'PWAM  ',     !6  XPDW 
     &    'H#AM  ',     !7  XNOGR
     &    'HWUM  ',     !8  XGWU 
     &    'H#UM  ',     !9  XNOGU
     &    'CWAM  ',     !10 XCWT 

!         08/11/2005 CHP
!         Change BWAH to BWAM -- by-product produced to maturity, but
!           not necessarily removed from field
!     &    'BWAH',     !11 XSWT 
     &    'BWAM  ',     !11 XSWT 

     &    'LAIX  ',     !12 XLAM 
     &    'HIAM  ',     !13 XHIN 
     &    'THAM  ',     !14 XTHR 
     &    'GNAM  ',     !15 XNGR 
     &    'CNAM  ',     !16 XNTP 
     &    'SNAM  ',     !17 XNST 
     &    'GN%M  ',     !18 XNPS 
     &    'CWAA  ',     !19 XCWAA
     &    'CNAA  ',     !20 XCNAA
     &    'L#SM  ',     !21 XLFNO
     &    'EDAT  ',     !22 Emergence date
     &    18*'      '/  
 `
These lines of code show the hard-coded structure used to associate the column names in the FileX with the output file.

Conclusion is that there is no error or mislabeled columns. The variables match what is inside the Fortran code.

Also, confirming what Dr. Hoogenboom mentioned : "Yes, that's correct. Currently FileA is read by the model only and there are smarts to associate the Year with the DOY value."

Thank you so much,

Fabio Oliveira
