### ISSUE TITLE
how to run GenCalc ? code does not seem to be available in dssat-csm-os 

### ISSUE THREAD

**Issue by NadaBenMhenni** [DSSAT/dssat-csm-os#332]
dssat-csm-os doesn't seem to have GenCalc code.

**Comment by fabiooliveira72** [comment]
Hi @NadaBenMhenni!

Gencalc is a different independent tool. You can run using the DSSAT-Shell. Unfortunately, the source code is not available on Github. You are not going to find in the dssat-csm-os repo.

Thank you!

**Comment by NadaBenMhenni** [comment]
@fabiooliveira72, based on DSSAT COMMAND LINE USAGE:

> G   FileX      TrtNo Gencalc: Run single FileX and treatment #.

  and 

> T   BatchFile  NA    Gencalc: Batchfile lists experiments and treatments.            

                                                                         
Are these functional? I tried to use and the result was a simple run. Can you explain its use please? and whether it enables the use of Gencalc for calibration?

**Comment by fabiooliveira72** [comment]
Hi @NadaBenMhenni!

I have no clue. I am not sure what are the commands for GenCalc.

Please use the https://dssat.net/contact-us/ and write a message there. Then, possible Dr. Shelia can check on this.

Thank you.

**Comment by lpmorenoc** [comment]
@NadaBenMhenni Why did you decide to use GenCalc instead of GLUE or other calibration methods? 
Do you have time series data? If you have time-series data I would recommend that you use the Cultivar coefficient estimator for the cropping system model based on time-series data  (TSE) https://github.com/memicemir/TSE

**Comment by NadaBenMhenni** [comment]
@lpmorenoc, I have been using GenCalc on DSSAT Shell. Transiting to CLI, I want to know the availability of calibration methods. I am not sure whether GLUE is available on DSSAT Shell or for the CLI version. Do you have any knowledge regrading this matter?
Moreover, thank you for sharing about TSE. I am not familiar with it. I will be taking a look.
