### ISSUE TITLE
Flood damage in DSSAT? 

### ISSUE THREAD

**Issue by helsharif** [DSSAT/dssat-csm-os#340]
Hello,
Can DSSAT model crop damage due to flooding/too much water? I recall previous versions did not.

**Comment by fabiooliveira72** [comment]
Hi Helsharif!

Dr. Hoogenboom mentioned that current models include flooding stress for DUL < SW < SAT.

DUL is Upper limit or Field capacity.
SW is Soil water.
SAT is Saturated water content.

Please @helsharif use the https://dssat.net/contact-us/ channel for these questions.

Here in the issues we use when there is a bug or problem within the source code. Then we can have more people looking at this to give you a better answer.

Thank you. I hope you have great weekend
