### ISSUE TITLE
DSSAT Not recognizing irrigation filex information for reported dates or days after planting

### ISSUE THREAD

**Issue by helsharif** [DSSAT/dssat-csm-os#357]
Hello, 
After numerous trial-and-error, I am unable to get DSSAT to recognize the irrigation information in my filex file for the cases of irrigation on reported dates or irrigation on days after planting. I carefully followed the example filex from the DSSAT help, but when I run the simulation, irrigation is not applied on the dates set in the filex.

I'm attaching here a zip file containing my experiment file G0000001.MZX with all necessary input files and my DSSAT 4.8 executable (compiled for windows from the latest code available from github).

To run the simulation, unzip the contents to a folder, open Windows command prompt in that folder and run the command:
.\DSCSM048 A G0000001.MZX

The OVERVIEW.OUT file will say:
WATER BALANCE  : IRRIGATE ON REPORTED DATE(S)
 IRRIGATION     :        0 mm IN     0 APPLICATIONS

After checking my filex for errors, I think this is a bug in DSSAT. 
When I modify my filex however to run with automatic irrigation, the simulated crop does receive irrigation. It is only in "reported dates" or "days after planting" mode that no irrigation is applied. 

If someone can help me resolve this issue that would be greatly appreciated.

[Irrigate_Reported_Dates_Test.zip](https://github.com/DSSAT/dssat-csm-os/files/12308402/Irrigate_Reported_Dates_Test.zip)

**Comment by fabiooliveira72** [comment]
Hi @helsharif!

I checked your file. Your file is missing the irrigation level in treatment section. You need to select the irrigation level for your treatment.

Here is your file corrected (rename the extension back to MZX):
[G0000001.txt](https://github.com/DSSAT/dssat-csm-os/files/12308606/G0000001.txt)

Please use the https://dssat.net/contact-us/ for questions, even if you think is a bug. We can check and then open an issue afterwards if needed.

Thank you.

Fabio Oliveira
