### ISSUE TITLE
Negative LAFR value in WHCRP048.CUL

### ISSUE THREAD

**Issue by mehmoodmz** [DSSAT/dssat-csm-os#362]
I was looking into the CROPSIM cultivar file and found the LAFR value of -0.10 for the NEWTON cultivar. However, the guidance about the maximum and minimum values for that parameter suggests values between 0.01 to 5.00. I want to clarify whether is this a typo or not.

https://github.com/DSSAT/dssat-csm-os/blob/684ff2b303854953f5a6ce6b4cfa06df1a0b183b/Data/Genotype/WHCRP048.CUL#L72

https://github.com/DSSAT/dssat-csm-os/blob/684ff2b303854953f5a6ce6b4cfa06df1a0b183b/Data/Genotype/WHCRP048.CUL#L62-L67

**Comment by fabiooliveira72** [comment]
Hi @mehmoodmz 

Thanks for catching this issue. We have been made a fix. We set equal to 0.00 LAFR.

We will have more evaluation of this coefficient value soon and then re-update if needed.

Thank you.

Fabio Oliveira
