### ISSUE TITLE
Rice simulation hangs (infinite loop?) based on soil percolation value

### ISSUE THREAD

**Issue by helsharif** [DSSAT/dssat-csm-os#368]
Hello,
In multiple tests of a flooded rice simulation, I am finding that DSSAT will hang indefinitely and not produce any output. So far I traced the potential source of this issue to the user-defined soil percolation rate in the fileX (IRVAL when IROP = IR008). In the attached example run, if the percolation rate in the filex is 3 mm/day, DSSAT hangs (as if stuck in an infinite loop). If I change the percolation to 2 mm/day or 4 mm/day DSSAT produces results in seconds with no problem. 

I did multiple tests with slightly different weather data, and I could reproduce the hanging with different values of the percolation rate (in the example case, 3 mm/day percolation caused the issue, but in other experiments, different values would cause the issue). So it seems there is some combination of weather, percolation rate, and maybe other parameters that cause DSSAT to get stuck.

To run the example case, unzip the contents of the attached zip and run 

DSCSM048 A G0000008.RIX

in the Windows Command Prompt. 

I'm hoping it is possible to solve this issue or find a suitable workaround.

Best regards

[DSSAT_Rice_Sim.zip](https://github.com/DSSAT/dssat-csm-os/files/12409023/DSSAT_Rice_Sim.zip)

_Note: edited post to have the correct command line command: DSCSM048 A G0000008.RIX_

**Comment by helsharif** [comment]
Hello, I was wondering if someone can help me on the DSSAT hanging on the rice simulation? I am running into the same problem more often and makes it impossible for me to complete models runs. I am noticing that DSSAT with the parameters/weather/etc. as set in the example data provided will hang on a particular day of the model run , but I don't know what exactly is causing the hang on that particular day of the growing season.

**Comment by chporter** [comment]
I can recreate the problem with the exe you provided. But with the latest source code on github, this problem does not occur. Can you try recompiling with the latest develop branch code at https://github.com/dssat/dssat-csm-os ?
Cheers,
Cheryl

**Comment by helsharif** [comment]
Hi, thank you for your help. Last night I re-downloaded the develop branch code and recompiled the dssat executable, but I'm still running into the same problem when I replace the executable. 

The recompiled executable says DSSAT Version: "4.8.1.046"
while the old (included in the zip of the original post) says "4.8.1.027"

In the zip below, is the new executable I'm using (still having the same problem)

[dscsm048_4_8_1_046.zip](https://github.com/DSSAT/dssat-csm-os/files/12478264/dscsm048_4_8_1_046.zip)

I wonder if the Fortran compiler I'm using could be an issue? I used GNU 9.2.0 for my fortran compiler.

**Comment by helsharif** [comment]
Hello, a quick update today. I downloaded the latest version GNU Fortran compiler I could find (GNU 13.2.0) and recompiled the latest development branch again. Now I was able to get the example case to run! So it looks like the issue was the relatively old compiler. I will keep running more test cases to see if the problem comes up again. Thank you so much again for your help!

**Comment by chporter** [comment]
Thanks for letting us know that you solved the problem. It may have been a compiler bug with that GNU 9.2.0. We try to make the code as portable as possible so it works on any platform.
