### ISSUE TITLE
is it a bug?

### ISSUE THREAD

**Issue by AryaFeng** [DSSAT/dssat-csm-os#377]
in the utilities/ModuleDefs.for file, at line 738-759(code)
      Case ('ORGC')
        SELECT CASE (VarName)
        Case ('MULCHMASS');Value = SAVE_data % ORGC % MULCHMASS
        Case ('TOMINFOM'); Value = SAVE_data % ORGC % TOMINFOM
        Case ('TOMINSOM'); Value = SAVE_data % ORGC % TOMINSOM
        Case ('TOMINSOM1');Value = SAVE_data % ORGC % TOMINSOM1
        Case ('TOMINSOM2');Value = SAVE_data % ORGC % TOMINSOM2
        Case ('TOMINSOM3');Value = SAVE_data % ORGC % TOMINSOM3
        Case ('TNIMBSOM'); Value = SAVE_data % ORGC % TNIMBSOM
        Case DEFAULT; ERR = .TRUE.
        END SELECT

      Case ('SOIL')
        SELECT CASE (VarName)
        Case ('TOMINFOM'); Value = SAVE_data % ORGC % TOMINFOM
        Case ('TOMINSOM'); Value = SAVE_data % ORGC % TOMINSOM
        Case ('TOMINSOM1');Value = SAVE_data % ORGC % TOMINSOM1
        Case ('TOMINSOM2');Value = SAVE_data % ORGC % TOMINSOM2
        Case ('TOMINSOM3');Value = SAVE_data % ORGC % TOMINSOM3
        Case ('TNIMBSOM'); Value = SAVE_data % ORGC % TNIMBSOM
        Case DEFAULT; ERR = .TRUE.
        END SELECT
in the case soil, the varName and SAVE_data % ORGC( i guess it should be SAVE_data % SOILPRO).It was originally like this, or could there still be a problem?
![1](https://github.com/DSSAT/dssat-csm-os/assets/69587189/fea67e1f-e6ec-4e05-9890-27fa35d40a4b)

**Comment by fabiooliveira72** [comment]
Hi @AryaFeng!

This is not a bug. Just code replicated. This is something we could remove for 'SOIL'

It is only used for 'ORGC' not soil.

Thank you!
