### ISSUE TITLE
Climate change impacts on abiotic stresses in DSSAT

### ISSUE THREAD

**Issue by LenLon** [DSSAT/dssat-csm-os#387]
Hello DSSAT team,

I am writing here as I am new to DSSAT and can't find what I am looking for in the documentation. I want to do some climate change impact studies on cereal and maize cropping systems in SSA, so marginal conditions with little to no fertilisation and irrigation. Now I have some questions before I start delving into preparation of input data and setup of my simulation:

- Are abiotic stresses, esp. heat and drought stress, implemented in DSSAT and if yes, to which degree and for which crop?
- How are extremes regarding temperature and drought handled in DSSAT in general? Do they affect other variables beyond soil and crop, such as pest damage?
- Is CO2 fertilisation implemented? Can I modify CO2 concentrations as part of an e.g. climate input file? Are there limits on possible CO2 concentrations, or could I use pre-industrial baseline concentrations (< 280 ppm)?

That is it for now, and I hope some can answer these questions, as I am quite curious about DSSAT and its applicability in this space!

Best,
Lennart

**Comment by fabiooliveira72** [comment]
Hi @LenLon!

Thanks for your message and interest in DSSAT but please next time for questions use contact us channel at https://dssat.net/contact-us

Answering your question. We would advise you to download DSSAT at http://dssat.net and go through the documentation where you will find several papers talking about that. All your questions are answered there, especially the 2019 DSSAT Chapter.

Through here would be very difficult to explain in details and the papers are a better resource.

Thank you.

Fabio Oliveira
