### ISSUE TITLE
relative path issue for CSM

### ISSUE THREAD

**Issue by Eugllena** [DSSAT/dssat-csm-os#390]
Hi, when I called CSM using relative path on Linux, for example, ../dscsm048 A UFCI0301.SWX, the program fail and return "Configuration file not found". When I use the absolute path: /home/fa/run/dscsm048 A UFCI0301.SWX, the program did not come across with the problem.
I found that when I use the relative path, the program wrongly searching the file DSSATPRO.L48 with the path "/DSSAT48/DSSATPRO.L48". I found out that replacing the number 8 with 12 will solve the problem.

**Comment by fabiooliveira72** [comment]
Hi @Eugllena 

Yes, the program will not run because of the DSSATPRO.L48. You have two choices, changing the DSSATPRO for the specific path or using the DSSAT_HOME env variable.

Thank you.

Fabio Oliveira
