### ISSUE TITLE
Review of MIN/MAX P/G parameters range for MZCER

### ISSUE THREAD

**Issue by Murilodsv** [DSSAT/dssat-csm-os#403]
We have a student from Togo who is having issues calibrating phenology with MZCER which is apparently because the MAX value of P5 is too low.  

https://github.com/DSSAT/dssat-csm-os/blob/1031deb1952aedce1ddd8f601a6d07349176c348/Data/Genotype/MZCER048.CUL#L47-L52

There are even examples of cultivars with P5>999:
https://github.com/DSSAT/dssat-csm-os/blob/1031deb1952aedce1ddd8f601a6d07349176c348/Data/Genotype/MZCER048.CUL#L259

**Should these MAX/MIN ranges be updated?**

**Comment by GerritHoogenboom** [comment]
Murilo,

Thank you for your comment. As you can see, values above 999 are rare and one is commented out. Make sure that your student is calibrating using a non-stressed treatment and using harvest maturity and NOT the harvest date. Currently GLUE is limited to a max value of 999.99.

Regards,

Gerrit

**Comment by Murilodsv** [comment]
Thanks Gerrit!

We have assumed no delay due to photoperiod (P2=0.0), which may be the culprit for such high P5 values. In any case, we'll review the dataset again. I'll close the ticket for now and re-open in future if needed.

Best regards,
Murilo
