### ISSUE TITLE
Broken CHM Files in Data/Help Directory

### ISSUE THREAD

**Issue by RFYoung** [DSSAT/dssat-csm-os#405]
Hello ,

I've found that the CHM files in the Data/Help folder seem to be broken. It is possible to replace them with working ones? 

By the way, the CHM files in the DSSAT full version are working fine.

Thanks for your help!

Best,
RFYoung

**Comment by chporter** [comment]
I can reproduce the problem. The chm files in the DSSAT repo are broken. I don't know if this is a github limitation. @fabiooliveira72 @thiagoferreira53 , any ideas?

**Comment by fabiooliveira72** [comment]
Hi @RFYoung and @chporter!

Yes, I believe this is a GitHub limitation. I believe these chm files need to be compiled to show the content. I do not think GitHub has this option and also seems the file is too big to show in raw format.

I just double checked the files on DSSAT Help menu and they are working.

Thank you.
