### ISSUE TITLE
Clarification around licensing: BSD3 or Proprietary?

### ISSUE THREAD

**Issue by pcboy** [DSSAT/dssat-csm-os#419]
I'm a bit confused about the license of DSSAT at the moment as there is conflicting information.  
The license in the repository mentions BSD3.  
But this file is also present in the repository

https://github.com/DSSAT/dssat-csm-os/blob/develop/Data/Help/DSSAT%20v4.8%20License%20%26%20Warranty%20Agreement.pdf

And shows:

> This license and warranty agreement is a legal document between you (either
> an individual or a single entity) and the DSSAT Foundation that includes certain limited rights for use of the
> **proprietary** DSSAT software and related materials. **All rights not specifically granted in this Agreement are
> reserved to the DSSAT Foundation**

> Grant of License:
> 1. DSSAT should be installed on a single computer.
> Description of Other Rights and Limitations:
> 1. Rental: You may not sell, rent, lease, sublicense, lend, time-share or transfer, in a whole or in part, or
> provide unlicensed parties access to prior or present versions of the DSSAT software and related
> Materials, any updates, or your rights under this Agreement.
> 2. Termination: Without prejudice to any other rights, the DSSAT Foundation may terminate this
> Agreement if you fail to comply with the terms and conditions of this Agreement. In such an incident,
> you must destroy all copies of the SOFTWARE PRODUCT and its component parts.

This seems to be incompatible to being a BSD3 license. Where even commercial use should be authorized.  
Did something change? Is it specific to DSSAT48?

**Comment by chporter** [comment]
The BDS3 license is for the DSSAT Cropping System Model in the dssat-csm-os repository. The license you refer to here is for the accompanying Windows software which can be used to enter DSSAT data and to interpret and analyze DSSAT outputs. This license is included in the DSSAT windows software release and is stored in this repo only to enable quick build of install files.

**Comment by pcboy** [comment]
I see. Thanks for the clarification. 

But this current repository does not contain any Windows code. Why is this file in this repository and not part of the closed source repository of the Windows version? I'm not sure I understand why and this may lead to potential confusion.

**Comment by fabiooliveira72** [comment]
@pcboy

Yes, indeed. It can lead to potential confusion. But it is based on what Cheryl said. One is for the repository and the others for the Windows software by the time the DSSAT Shell is built.

Thank you.

Fabio Oliveira
