### ISSUE TITLE
Rye-grass genotype files seem missing 

### ISSUE THREAD

**Issue by ibrahimasow** [DSSAT/dssat-csm-os#425]
Hi team, 

rye-grass .cul, .eco and .spe files are missing from ./Data/Genotype even though the crop is listed [here](https://dssat.net/plant-growth-modules-in-dssat-csm/).

**Comment by fabiooliveira72** [comment]
@ibrahimasow 

Thanks for your observation. But not yet. Do not consider in the website. If the crop is not under SIMULATION.CDE the model will not be able to simulate. This web page may be created and not updated anymore. We will probably add in the future.

Thank you.

Fabio Oliveira

**Comment by ibrahimasow** [comment]
Got it, thank you Fabio
