### ISSUE TITLE
about Automatic N-fertilization routine no longer supported?

### ISSUE THREAD

**Issue by xiangyi-wang** [DSSAT/dssat-csm-os#428]
I noticed that Automatic N-fertilization routine was commented outin v4.7.5.14 as to whether it was being used differently or was no longer supported

![66ec3107bdcf3f098805a2b3f114cae](https://github.com/user-attachments/assets/e6ccae2c-8dd5-4645-a09c-dd55a2a14f9d)

**Comment by chporter** [comment]
This method was not very stable and we removed it from the release version of the model.

**Comment by xiangyi-wang** [comment]
Thank you

**Comment by xiangyi-wang** [comment]
> Thank you

**Comment by xiangyi-wang** [comment]
@chporter What kind of impact does instability refer to

**Comment by chporter** [comment]
Sorry, it has been quite a few years since I looked at this. I don't remember exactly what the issues were except that we weren't happy with the model outcomes.

We recently introduced automatic irrigation using growth-stage dependent rules. I think something similar could be added for fertilizer. Are you a programmer?

**Comment by xiangyi-wang** [comment]
> Sorry, it has been quite a few years since I looked at this. I don't remember exactly what the issues were except that we weren't happy with the model outcomes.
> 
> We recently introduced automatic irrigation using growth-stage dependent rules. I think something similar could be added for fertilizer. Are you a programmer?

Thank you very much for your reply. I am a programmer with some Fortran programming experience, but not too much. Perhaps I can give it a try.

**Comment by chporter** [comment]
Here is the user guide for this feature. The growth stages used for fertilizer would be similar, but the rules might be for a single application of a fixed amount of fertilizer when a growth stage is reached. Let me know if you have questions. 
[DSSAT_User_guide to automatic Irrigation using Growth Stage Controls_v8.pdf](https://github.com/user-attachments/files/16343401/DSSAT_User_guide.to.automatic.Irrigation.using.Growth.Stage.Controls_v8.pdf)

**Comment by xiangyi-wang** [comment]
> 这是此功能的用户指南。用于施肥的生长阶段类似，但规则可能是在达到生长阶段时一次性施用固定量的肥料。如果您有任何问题，请告诉我。DSSAT_User_guide [to automatic Irrigation using Growth Stage Controls_v8.pdf](https://github.com/user-attachments/files/16343401/DSSAT_User_guide.to.automatic.Irrigation.using.Growth.Stage.Controls_v8.pdf)

Thanks again
