### ISSUE TITLE
Simulating Residue*Fertilizer levels using the Sequence Application

### ISSUE THREAD

**Issue by smkuhlani** [DSSAT/dssat-csm-os#430]
I am attempting to simulate a rotation based conservation agriculture experiment with Residues (Zero and 10 000 kg/ha) and Fertilizer (0, 60, 120 and 180N kg/ha), using the Sequential Option in DSSAT. 

issue: 1-In theory, every season i expect to see a yield value for each of the Treatment combinations, but instead i get the opposite. 2-The Output is not a normal Sequence simulation output (.OSU) but rather a normal experimental one (Summary.OUT).

[Sequence_Try.zip](https://github.com/user-attachments/files/16348109/Sequence_Try.zip)

**Comment by chporter** [comment]
When running sequence files, run only one treatment at a time. We recommend that each treatment be a separate FileX and that they be run separately. You can combine them into one FileX as you have done, but run them one at a time.

To get the output names tied to the FileX name, set the FNAME option in Simulation Controls to "Y". In XBuild: Simulation Options --> Outputs --> Output Files --> Experiment.

**Comment by fabiooliveira72** [comment]
@chporter!

I am closing this issue. It seems you answered the question than an issue.

Thank you.

Fabio Oliveira
