### ISSUE TITLE
Soil nitrogen is not balanced for CROPSIM models

### ISSUE THREAD

**Issue by lpmorenoc** [DSSAT/dssat-csm-os#69]
The plant N uptake for the CROPSIM models (CSCER,CSCRP,CSCAS,CSYCA) is done when DYNAMIC == RATE while for the CROPGRO models is when DYNAMIC == INTEGR.  The CROPGRO models have a soil N balance of 0 while it is not like that for the CROPSIM models.  
![image](https://user-images.githubusercontent.com/6476135/107826072-39d5f080-6d52-11eb-9e2f-5d6e76a6bddf.png)

![image](https://user-images.githubusercontent.com/6476135/107826184-71dd3380-6d52-11eb-90c9-509d19199d90.png)

**Comment by chporter** [comment]
This has been solved with commit 18de615d4694ec2c2b5a0043219919d399d7733b
