### ISSUE TITLE
Example dataset/invocation of DSSAT

### ISSUE THREAD

**Issue by adarshp** [DSSAT/dssat-csm-os#7]
Hi @chporter , @GerritHoogenboom and @frostbytten ,

We are trying to do a test run of DSSAT with some representative inputs in order to make sure that our program analysis pipeline produces outputs that are faithful to the original code.

Would it be possible to get an example dataset and invocation of the `dscsm047` executable to see if we can generate the expected outputs? I managed to get the following output:

```





















RUN    TRT FLO MAT TOPWT HARWT  RAIN  TIRR   CET  PESW  TNUP  TNLF   TSON TSOC
           dap dap kg/ha kg/ha    mm    mm    mm    mm kg/ha kg/ha  kg/ha t/ha
  1 SB   1 -99 -99   -99   -99   -99   -99   -99   -99   -99   -99   -99      0
  2 SB   2 -99 -99   -99   -99   -99   -99   -99   -99   -99   -99   -99      0
  3 SB   3 -99 -99   -99   -99   -99   -99   -99   -99   -99   -99   -99      0
  4 SB   4 -99 -99   -99   -99   -99   -99   -99   -99   -99   -99   -99      0

```

By copying the following files (from the files sent by @chporter by email on 10/30/2018 from running the ASCE and PET options for a 1978 soybean experiment in Gainesville, FL) to the `Data` directory:

```
DSSBatch.v47
FERCH047.SDA
SBGRO047.CUL
SBGRO047.ECO
SBGRO047.SPE
SOIL.SOL
UFGA7801.SBX
dscsm047
```

and running the following command:

```
./dscsm047 B DSSBatch.v47
```

While the program runs to completion, the outputs seem funky, so I am fairly sure I am doing something wrong over here. We would be grateful for any help you could provide on this.

I'm tagging @skdebray , @cl4yton , and @pauldhein to keep them in the loop.

Thanks!

**Comment by chporter** [comment]
Hi, @adarshp 
Sorry I didn't see this earlier. 
I think you are missing the weather file.  It should be named UFGA7801.WTH. If you put it in the data directory, the model will find it. 
Please also include the CO2047.WDA file from the StandardData directory.

This latest version of the code has disabled the ASCE-K version of potential evapotranspiration. We did that because of some unintended consequences of those routines. (just so you know).

**Comment by adarshp** [comment]
@chporter I added the the `UFGA7801.WTH` and `CO2047.WDA` files, but am now getting the following exception:

```
(delphi) ~/github/dssat-csm-os/Data (develop) $ ./dscsm047 B DSSBatch.v47

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x110f2ea14
#1  0x110f2e136
#2  0x7fff69dc542c
#3  0x10f2a9d8c
#4  0x10f2aaa0e
#5  0x10f2ab774
#6  0x10f2a64d8
#7  0x10f2b2308
#8  0x10ee88665
#9  0x10ee869d4
#10  0x10f2c9673
Floating point exception: 8
```

**Comment by chporter** [comment]
@adarshp We finalized this outside github, so I'm closing the issue.
