### ISSUE TITLE
how to simulate the effect of soil stress on rice yield?

### ISSUE THREAD

**Issue by mrsunhuang** [DSSAT/dssat-csm-os#71]
Excuse me, does anyone know how to simulate the effect of soil stress on rice yield?please

**Comment by chporter** [comment]
Hi, @mrsunhuang , please use the DSSAT.net contact page for general questions about the model https://dssat.net/contact-us/. This issues page is to report bugs with the model code.

The Ceres-rice model does simulate the effects of soil water and soil N deficiencies affecting plant growth and photosynthesis. You can see a report of these stresses in Overview.OUT and PlantGro.OUT.
